[package]
name = "sqlx-query-cel"
description = "CEL filter -> WhereClause for sqlx-query"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lints]
workspace = true

[dependencies]
sqlx-query = { path = "../sqlx-query" }
cel = { workspace = true }
thiserror = { workspace = true }
